<?php
// Generated by fix-prod-ready.sh
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CreateHolidayRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        return [
            'holiday_date' => 'required|date|after_or_equal:today',
            'reason' => 'nullable|string|max:255',
            'provider_id' => ['required', 'exists:providers,id', Rule::when(request()->user()->hasRole('provider'), 'in:' . request()->user()->providers()->first()?->id ?? 0)],
        ];
    }
}

